### ISSUE TITLE
Video broken

### ISSUE THREAD

**Issue by lagatameowmix** [learn-co-curriculum/first-html-tag-lab#1]
The video on the First HTML Tag lesson is not connecting. 
![screen shot 2017-11-05 at 11 59 26 am](https://user-images.githubusercontent.com/33333319/32418540-da694e60-c220-11e7-8407-4722d6e60e5d.png)

**Comment by lagatameowmix** [comment]
the link works, just the embedded video is broken

**Comment by aviflombaum** [comment]
Hmm...works for me, might be a temp glitch or youtube or your browser. Sorry about that!
