### ISSUE TITLE
Submitting the lesson doesn't reflect on the lesson page

### ISSUE THREAD

**Issue by safuya** [learn-co-curriculum/first-html-tag-lab#5]
I've got the tests passing and submitted the lesson, and the lesson page hasn't updated to show a pull request.

The [pull request](https://github.com/learn-co-students/first-html-tag-lab-v-000/pull/205) exists.

**Comment by maxwellbenton** [comment]
Hi @safuya,

Thank you for sending feedback and opening an issue.  Unfortunately, I'm having difficulty replicating the issue, as it looks like the lesson is functioning as expected.  You can try deleting your pull request and forking the lesson again, but ultimately, if you feel good about the content, you are fine to continue.  Your pull request is showing up within learn.co's admin page, so if there is any concern later on about incomplete lessons, there is a link to the PR showing you've completed the work.

I am going to close this issue for now, but if this continues to be an issue on upcoming lessons, I would recommend opening an Ask a Question on learn.co.  The technical coaches may have a different solution to this issue.
