### ISSUE TITLE
Link in lesson/lab is broken

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/first-html-tag-lab#7]
The link to the help article talking about how to view html pages in the learn IDE is incomplete.

This is what it currently is:
http://help.learn.co/the-learn-ide/common-ide-questions/viewing-

This is what it should be:
http://help.learn.co/the-learn-ide/common-ide-questions/viewing-html-pages-in-the-learn-ide

**Comment by drakeltheryuujin** [comment]
Looks like this has already been fixed
